### ISSUE TITLE
Add support for IORING_SETUP_TASKRUN_FLAG and IORING_SETUP_COOP_TASKRUN when using a 5.19 kernel

### ISSUE THREAD

**Issue by danielealbano** [danielealbano/cachegrand#134]
Add support for IORING_SETUP_TASKRUN_FLAG and IORING_SETUP_COOP_TASKRUN when using a 5.19 kernel

**Comment by beef9999** [comment]
Maybe could use our lib directly?
https://github.com/alibaba/PhotonLibOS

**Comment by danielealbano** [comment]
cachegrand's programing language is C, it wouldn't be a good idea to mix and match C and C++ for such a critical functionality.

Also l, this specific enhancement is fairly simple to add as its literally an if and setting a variable :) it's not worth to rewrite a ton of code just for that :)

**Comment by beef9999** [comment]
Does your project have coroutine/fiber?

Or is it running in the async callback mode?

**Comment by danielealbano** [comment]
I have my own fiber implementation
