### ISSUE TITLE
Prometheus endpoint Segfaults

### ISSUE THREAD

**Issue by justinholmes** [danielealbano/cachegrand#344]
Prometheus endpoint Segfaults

## Steps to reproduce:
Enable Prometheus in the config.
Go to metrics endpoint (http://127.0.0.1:9090/metrics).
Segfault happens.

## Config file
Just enable Prometheus
  - type: prometheus
    network:
      timeout:
        read_ms: -1
        write_ms: 10000
      bindings:
        - host: 0.0.0.0
          port: 9090

## Hardware and Operating System
Ubuntu 22.04

**Comment by danielealbano** [comment]
Fixed with v0.4.0, the issue was related to the monotonic clock management
